spring.application.name=programacion-service
server.port=8086

spring.datasource.url=${MYSQL_PROGRAMACION_URL:jdbc:mysql://localhost:3306/sitrac_programaciones?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Lima}
spring.datasource.username=${MYSQL_USER:root}
spring.datasource.password=${MYSQL_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.error.include-message=always

services.pedido.url=${PEDIDO_SERVICE_URL:http://localhost:8083}
services.conductor.url=${CONDUCTOR_SERVICE_URL:http://localhost:8084}
services.flota.url=${FLOTA_SERVICE_URL:http://localhost:8085}
