spring.application.name=conductor-service
server.port=8084

spring.datasource.url=${MYSQL_CONDUCTOR_URL:jdbc:mysql://localhost:3306/sitrac_conductores?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Lima}
spring.datasource.username=${MYSQL_USER:root}
spring.datasource.password=${MYSQL_PASSWORD:Yprogramacion2025}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always
